Features/docs aggregation
oemof/oemof-thermal pull request #121
Opened 2020-05-26 10:56 UTC by MaGering

With this PR the documentation of the theoretical considerations towards the aggregation of domestic decentral solar thermal systems is created.

Related issues: https://github.com/oemof/oemof-thermal/issues/120 and https://github.com/oemof/oemof-solph/issues/647

The structure of the section in the documentation is based on the content of issue https://github.com/oemof/oemof-solph/issues/647.

2020-06-23 12:38 UTC, c-moeller requested changes
I added some small changes.

And one request: Could you put the section "Theoretical considerations" on the same level as "User's Guide". And "Aggregation..." on the same level as the components in "User's Guide"

And one more remark: We should have some kind of nomenclature, even though the symbols seem self-explanatory. So, if it is not too much effort, you could add a small table (but I would say with lower priority).

2020-06-23 12:38 UTC, c-moeller commented on docs/theoretical_considerations.rst
> +Usually these ratios are constant within the two types.
```suggestion
Normally there are typical ratios which are used when dimensioning these types of systems.
```

2020-06-23 12:38 UTC, c-moeller commented on docs/theoretical_considerations.rst
> +So it is possible to aggregate the houses within one type and define the ratios. This would be more accurate than an aggregation of all installed systems.
```suggestion
So it is possible to aggregate the houses within one type by defining these ratios. This would be more accurate than an aggregation of all installed systems.
```

2020-06-23 12:38 UTC, c-moeller commented on docs/theoretical_considerations.rst
> +If there are special system modifications, there can be defined more than two groups.
```suggestion
In case of special system modifications, also more than two groups could be defined.
```

2020-06-23 12:38 UTC, c-moeller commented on docs/theoretical_considerations.rst
> +Instead of aggregate all storages and all collectors of the systems, which would be really unaccurate, we want to classify two different types of domestic solar systems:
```suggestion
Instead of aggregate all storages and all collectors of the system, which would be really unaccurate, we want to classify two different types of domestic solar systems:
```

2020-06-23 13:47 UTC, MaGering commented
> And one more remark: We should have some kind of nomenclature, even though the symbols seem self-explanatory. So, if it is not too much effort, you could add a small table (but I would say with lower priority).

I've added a first draft of a nomenclature in the section 'Aggregation...'. Could you please check it and round it off @c-moeller ?

2020-07-03 09:56 UTC, c-moeller approved these changes

2020-07-03 09:56 UTC, merged