Features/docs validation heatpump chiller
oemof/oemof-thermal pull request #158
Opened 2020-08-04 13:16 UTC by MaGering

With this PR the validation of the compression heat pump and chiller is described in the documentation.

Related: Issue #126 (comment)

2020-09-01 12:32 UTC, MaGering commented
The documentation of the validation can be accessed using the following link leading to the version of this branch: https://oemof-thermal.readthedocs.io/en/features-docs-validation-heatpump-chiller/

2020-09-09 13:47 UTC, SabineHaas commented
> The documentation of the validation can be accessed using the following link leading to the version of this branch: https://oemof-thermal.readthedocs.io/en/features-docs-validation-heatpump-chiller/

@MaGering / @c-moeller could you activate the readthedocs page for the review again please? Right now there's only master, latest, and stable -->https://oemof-thermal.readthedocs.io/en/latest/   Thank you :)

2020-09-09 13:54 UTC, MaGering commented
> @MaGering / @c-moeller could you activate the readthedocs page for the review again please? Right now there's only master, latest, and stable -->https://oemof-thermal.readthedocs.io/en/latest/ Thank you :)

Done. :) 
I'm wondering why it disappeared in the first place. Does anyone have an idea?

2020-09-09 14:19 UTC, SabineHaas commented
> > @MaGering / @c-moeller could you activate the readthedocs page for the review again please? Right now there's only master, latest, and stable -->https://oemof-thermal.readthedocs.io/en/latest/ Thank you :)
> 
> Done. :)
> I'm wondering why it disappeared in the first place. Does anyone have an idea?

Thank you :) 
Maybe somebody switched it off not knowing that we were using it temporarily.

2020-09-09 15:12 UTC, SabineHaas requested changes
Thanks a lot @MaGering for your great work! 

I tried to mostly suggest changes instead of commenting. Feel free to rephrase my suggestions, of course ;)

2020-09-09 15:12 UTC, SabineHaas commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +`GRECO project <https://github.com/greco-project>`_.
```suggestion
`GRECO project <https://www.greco-project.eu/>`_ in collaboration with the `oemof_heat project
<https://github.com/oemof-heat>`_.
```

2020-09-09 15:12 UTC, SabineHaas commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +`GRECO project <https://github.com/greco-project>`_.
You might want to give an appropriate link for oemof_heat, too. 
@c-moeller do you agree with the sentence?

2020-09-09 15:12 UTC, SabineHaas commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +** TODO: what technology - air to air? **
yes it's air-to-air

2020-09-09 15:12 UTC, SabineHaas commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +Politécnica de Madrid (UPM).
```suggestion
Politécnica de Madrid (UPM). An open access publication containing further description of the data and experiments done in [2] is planned for November 2020.
```

2020-09-09 15:12 UTC, SabineHaas commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +Politécnica de Madrid (UPM).
Could you add a reference to https://www.sciencedirect.com/science/article/abs/pii/S0038092X2030596X please?

2020-09-09 15:12 UTC, SabineHaas commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +The set of data contains amongst others external and internal temperatures of the components and a calculated
```suggestion
The set of data contains amongst others external and internal flow temperatures of the components and a calculated
```

2020-09-09 15:12 UTC, SabineHaas commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +points. It further has multiple downtimes, which lead to reversed temperatures of heat sink and heat source.
> It further has multiple downtimes, which lead to reversed temperatures of heat sink and heat source.

Could you mention in just a sentence that these were filtered?

2020-09-09 15:12 UTC, SabineHaas commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +which corresponds to the difference of the monitored and calculated coefficients is used. For both, chiller and heat
```suggestion
which corresponds to the difference of the monitored and calculated coefficients, is used. For both, chiller and heat
```

2020-09-09 15:12 UTC, SabineHaas commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +
> The correlation with quality grades below 0.30 show an overestimation of the coefficients. In contrast, ...

I think it's the other way round. Looking at Fig.1 at the left side (qg 0.25): If the x-axis shows the calculated values and the y-axis the monitored values --> for example calculated value ~ 3.5-4, corresponding monitored value ~ 5. 
This might occur for other figures, too, I didn't check this.

2020-09-09 15:12 UTC, SabineHaas commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +Tab.2: Root square mean error for different quality grades of the heat pump
```suggestion
Tab.2: Root mean square error for different quality grades of the heat pump
```

2020-09-09 15:12 UTC, SabineHaas commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +Tab.1: Root square mean error for different quality grades of the chiller
```suggestion
Tab.1: Root mean square error for different quality grades of the chiller
```

2020-09-09 15:12 UTC, SabineHaas commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +
I think it would be nice to add a small section "conclusion" stating the main findings. Do you agree @MaGering  and @c-moeller ?

2020-09-09 15:14 UTC, SabineHaas commented
Ah sorry, I forgot one tiny thing: 
As discussed there should be a link to the repository where the code of the validation will be stored: https://github.com/greco-project/heat_pump_validation 

Thank you :)

2020-09-17 14:49 UTC, c-moeller requested changes

2020-09-17 14:49 UTC, c-moeller commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +`GRECO project <https://github.com/greco-project>`_.
Yes sounds good.

2020-09-17 14:49 UTC, c-moeller commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +`GRECO project <https://github.com/greco-project>`_.
https://github.com/oemof-heat

2020-09-17 14:49 UTC, c-moeller commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +** TODO: what technology - air to air? **
Please introduce the abbreviations.

2020-09-17 14:49 UTC, c-moeller commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +COP / EER value.
Coefficient of performance (COP)

2020-09-17 14:49 UTC, c-moeller commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +In order to calculate the COP and EER using oemof.thermal the temperature of the heat source, the temperature of the
```suggestion
In order to calculate the COP and EER using oemof-thermal the temperature of the heat source, the temperature of the
```

2020-09-17 14:49 UTC, c-moeller commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +The functionalities for calculating the COP and EER of oemof.thermal are made for a stationary process, while the data
```suggestion
The functionalities for calculating the COP and EER of oemof-thermal are made for a stationary process, while the data
```

2020-09-17 14:49 UTC, c-moeller commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +    (right).
```suggestion
    (right)
```

2020-09-17 14:49 UTC, c-moeller commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +    (right).
```suggestion
    (right)
```

2020-09-17 14:49 UTC, c-moeller commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +    0.35 (right).
```suggestion
    0.35 (right)
```

2020-09-17 14:49 UTC, c-moeller commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +    with least error (middle) and with underestimation connected to a quality grade of 0.35 (right).
```suggestion
    with least error (middle) and with underestimation connected to a quality grade of 0.35 (right)
```

2020-09-17 14:49 UTC, c-moeller commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +In Fig.5 this linearity can be seen for a quality grad of 0.05 (left graph) and a quality grade of 0.50 (right graph).
```suggestion
In Fig.5 this linearity can be seen for a quality grade of 0.05 (left graph) and a quality grade of 0.50 (right graph).
```

2020-09-17 14:49 UTC, c-moeller commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +    and a quality grade of 0.50 (right).
```suggestion
    and a quality grade of 0.50 (right)
```

2020-09-17 14:49 UTC, c-moeller commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +Tab.2: Root square mean error for different quality grades of the heat pump
Put table caption above table?

2020-09-17 14:49 UTC, c-moeller commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +Tab.1: Root square mean error for different quality grades of the chiller
Put table caption above table?

2020-09-17 14:49 UTC, c-moeller commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +    (right).
```suggestion
    (right)
```

2020-09-17 14:49 UTC, c-moeller commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +In Fig.7 shows the residual over monitored COP for quality grades of 0.30, 0.35 and 0.40. In Fig.8 the residual is
```suggestion
Fig.7 shows the residual over monitored COP for quality grades of 0.30, 0.35 and 0.40. In Fig.8 the residual is
```

2020-09-17 14:49 UTC, c-moeller commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +    (right).
```suggestion
    (right)
```

2020-09-17 14:49 UTC, c-moeller commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +    0.40 (right).
```suggestion
    0.40 (right)
```

2020-09-17 14:49 UTC, c-moeller commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +    with least error (middle) and with underestimation connected to a quality grade of 0.40 (right).
```suggestion
    with least error (middle) and with underestimation connected to a quality grade of 0.40 (right)
```

2020-09-17 14:49 UTC, c-moeller commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +    and a quality grade of 0.50 (right).
```suggestion
    and a quality grade of 0.50 (right)
```

2020-09-17 14:49 UTC, c-moeller commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +Looking at the whole preprocessed, monitored data, a linear dependence of the residuals to monitored COP values can
```suggestion
Looking at the whole preprocessed monitored data, a linear dependence of the residuals to monitored COP values can
```

2020-10-02 11:47 UTC, MaGering commented
> Ah sorry, I forgot one tiny thing:
> As discussed there should be a link to the repository where the code of the validation will be stored: https://github.com/greco-project/heat_pump_validation
> 
> Thank you :)

Done in https://github.com/oemof/oemof-thermal/pull/158/commits/86c2fabb50580a302eb561a3db923b90002bd7c2

2020-10-02 11:49 UTC, MaGering commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +Politécnica de Madrid (UPM).
Reference added in https://github.com/oemof/oemof-thermal/pull/158/commits/37a98982e882b9e786ae91ad91584d742be1ae40

2020-10-02 11:53 UTC, MaGering commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +Politécnica de Madrid (UPM).
Changes applied in https://github.com/oemof/oemof-thermal/pull/158/commits/8438e7eccb14a2fc78bb2b30c0004aba9b9eb1a3

2020-10-02 11:55 UTC, MaGering commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +** TODO: what technology - air to air? **
Both done in https://github.com/oemof/oemof-thermal/pull/158/commits/31b90223eaf7985887c31a9129c1a3028cf5e33d

2020-10-02 12:02 UTC, MaGering commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +COP / EER value.
Done in https://github.com/oemof/oemof-thermal/pull/158/commits/31b90223eaf7985887c31a9129c1a3028cf5e33d

2020-10-02 12:11 UTC, MaGering commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +Tab.2: Root square mean error for different quality grades of the heat pump
Done in https://github.com/oemof/oemof-thermal/pull/158/commits/a39fd0e456fd0918e766d3578629b72213af85e4

2020-10-02 12:11 UTC, MaGering commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +Tab.1: Root square mean error for different quality grades of the chiller
Done in https://github.com/oemof/oemof-thermal/pull/158/commits/a39fd0e456fd0918e766d3578629b72213af85e4

2020-10-02 12:51 UTC, MaGering commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +points. It further has multiple downtimes, which lead to reversed temperatures of heat sink and heat source.
Done in https://github.com/oemof/oemof-thermal/pull/158/commits/8e7a9abfb4d6a7a601b08ffb984e0d7d744f96ff

2020-10-02 13:27 UTC, MaGering commented on docs/validation_compression_heat_pumps_and_chillers.rst
> +
Makes perfect sense! :) Fixed in https://github.com/oemof/oemof-thermal/pull/158/commits/cfb8786118da0b47fe766dc6142b80b421df842f

2020-10-02 17:26 UTC, merged