Features/storage validation
oemof/oemof-thermal pull request #162
Opened 2020-09-15 16:43 UTC by jakob-wo

This PR adds a validation of the stratified thermal storage model to the documentation.
The code behind it (creates the figure) is added to the example section.

2020-09-16 09:00 UTC, jakob-wo commented
@c-moeller please have a look at the documentation and let me know if you understand how the validation was conducted from what I wrote so far.

2020-09-17 15:33 UTC, c-moeller requested changes
@jakob-wo Thank you for the validation! It reads good and understandable. I've just made some small remarks.

Could you give a final statement about the storage model below the figure? Does it calculate losses in an appropriate way for energy system analysis? And why are the measurement data fluctuating that much? Measuring inaccuracy?

And one final question: You did the validation for a quite high storage level. Maybe you can add a line, why this is sufficient. Or should we contrast a validation with lower storage levels?

2020-09-17 15:33 UTC, c-moeller commented on docs/validation_stratified_thermal_storage.rst
> +The validation of the stratified thermal storage has been conducted within the oemof_heat project.
Please link to https://github.com/oemof-heat

2020-09-17 15:33 UTC, c-moeller commented on docs/validation_stratified_thermal_storage.rst
> +component from oemof.thermal
```suggestion
component from oemof-thermal
```

2020-09-17 15:33 UTC, c-moeller commented on docs/validation_stratified_thermal_storage.rst
> +Tab.1: Input parameters used for the model validation.
```suggestion
Tab.1: Input parameters used for the model validation
```

2020-09-17 15:33 UTC, c-moeller commented on docs/validation_stratified_thermal_storage.rst
> +Tab.1: Input parameters used for the model validation.
Put caption above table?

2020-09-17 15:33 UTC, c-moeller commented on docs/validation_stratified_thermal_storage.rst
> +    temperature of hot layer        82 °C
```suggestion
    temperature of hot layer        82°C
```

2020-09-17 15:33 UTC, c-moeller commented on docs/validation_stratified_thermal_storage.rst
> +    temperature of cold layer       55 °C
```suggestion
    temperature of cold layer       55°C
```

2020-09-17 15:33 UTC, c-moeller commented on docs/validation_stratified_thermal_storage.rst
> +    temperature of environment      25 °C
```suggestion
    temperature of environment      25°C
```

2020-09-17 15:33 UTC, c-moeller commented on docs/validation_stratified_thermal_storage.rst
> +================================ =============================
For consistency reasons you could write "Data of the reference storage" as subcaption

2020-09-17 15:33 UTC, c-moeller commented on docs/validation_stratified_thermal_storage.rst
> +The measurement data come from a energy system that contains several identical storages.
```suggestion
The measurement data come from an energy system that contains several identical storages.
```

2020-09-17 15:33 UTC, c-moeller commented on docs/validation_stratified_thermal_storage.rst
> +The validation aims on checking how accurately the losses of the storage are predicted.
```suggestion
The validation aims on checking how accurately the losses of the storage are predicted by the model.
```

2020-09-17 15:33 UTC, c-moeller commented on docs/validation_stratified_thermal_storage.rst
> +time      level in %
```suggestion
Time      Level in %
```

2020-09-22 07:32 UTC, jakob-wo commented on docs/validation_stratified_thermal_storage.rst
> +The validation of the stratified thermal storage has been conducted within the oemof_heat project.
done!

2020-09-22 08:51 UTC, jakob-wo commented
@c-moeller, thank you for the review!

I added the missing text in the results section and considered your suggestions in the changes.
Please, have a look at the new text and let me know if it answers the questions sufficiently.

2020-09-23 15:49 UTC, c-moeller approved these changes
Looks good. Thank you.
I've just made some small change in the table. Sorry, maybe it was not clear what I meant.

2020-09-23 15:49 UTC, c-moeller commented on docs/validation_stratified_thermal_storage.rst
> +================================ =============================
```suggestion
================================ =============================
**Data of the reference storage**
--------------------------------------------------------------
```

2020-09-23 15:49 UTC, c-moeller commented on docs/validation_stratified_thermal_storage.rst
> +Tab.1: Data of the reference storage.
```suggestion
Tab.1: Input parameters used for the model validation
```

2020-09-23 16:12 UTC, jakob-wo commented
@c-moeller: Great! I am going to merge it then. Thank you.

2020-09-23 17:11 UTC, merged