Features/csp - concentrated solar power
oemof/oemof-thermal pull request #20
Opened 2019-11-06 13:55 UTC by FranziPl

This PR is related to the issue [#603](https://github.com/oemof/oemof/issues/603) in oemof/oemof and add a new component for the calculation of a parabolic trough collector. 
It contains:
- [X] precalculation of the collector (Output: collectors heat)
- [ ] Facade, which combines the collector with a bus and a component, which holds the electric consumption of the pumps and the thermal losses of the collector 
- [X] example, which shows the usage of the precalculations
- [ ] example, which shows the usage of the hole facade
- [ ] documentation

There is a file for the precalculations and an example, which I consider as ready to review. The documentation is need to be changed (by myself) and the facade doesn't exist yet.

2019-11-06 15:33 UTC, FranziPl commented
@c-moeller, please have a look at the precalculation and the example. The rest will follow later.

2019-11-14 12:38 UTC, c-moeller commented on docs/concentrating_solar_power.rst
> +solar collector based on the horizontal direct irradiance or the direct normal
```suggestion
solar collector based on the direct horizontal irradiance (DHI) or the direct normal
```

2019-11-14 12:39 UTC, c-moeller commented on docs/concentrating_solar_power.rst
> +irradiance and information about the collector and the location. The processing
```suggestion
irradiance (DNI) and information about the collector and the location. The processing
```

2019-11-14 12:40 UTC, c-moeller commented on docs/concentrating_solar_power.rst
> +irradiance and information about the collector and the location. The processing
I added the abbreviations because they are quite common and might help to capture what is done.

2019-11-14 12:41 UTC, c-moeller commented on docs/concentrating_solar_power.rst
> +The efficiency on the collector is calculated with
```suggestion
The efficiency of the collector is calculated with
```

2019-11-14 12:53 UTC, c-moeller commented on examples/CSP/CSP_example.py
> +                           435, 500,
You could think about defining the variables beforehand. Now it's quite confusing which value belongs to which variable and makes it hard to run simulations with sensitivities.

2019-11-14 12:56 UTC, c-moeller commented on src/oemof/thermal/CSP.py
> +        holding values for time, the irradiance and the ambient temperature
```suggestion
        Holds values for time, the irradiance and the ambient temperature.
```

2019-11-14 12:56 UTC, c-moeller commented on src/oemof/thermal/CSP.py
> +        defines the number of timesteps
```suggestion
        Defines the number of timesteps.
```

2019-11-14 12:56 UTC, c-moeller commented on src/oemof/thermal/CSP.py
> +        latitude of the location
```suggestion
       Latitude of the location.
```

2019-11-14 12:58 UTC, c-moeller commented on src/oemof/thermal/CSP.py
> +            describes the name of the column in the dataframe df
I think the convention is capital letter at the beginning and period at the end, see suggestions above. Correct me, if I'm wrong.

2019-11-14 12:59 UTC, c-moeller commented on src/oemof/thermal/CSP.py
> +            degrees East of North
Wrong indentation?

2019-11-14 13:00 UTC, c-moeller commented on src/oemof/thermal/CSP.py
> +            given and used for Calculation
```suggestion
            given and used for calculation
```

2019-11-14 13:26 UTC, c-moeller commented on src/oemof/thermal/CSP.py
> +            describes the name of the column in the dataframe df
Wrong indentation?

2019-11-14 13:29 UTC, c-moeller commented on src/oemof/thermal/CSP.py
> +    if you have no idea, which values your collector have, here are values,
```suggestion
    If you have no idea, which values your collector have, here are values,
```

2019-11-14 13:34 UTC, c-moeller commented on src/oemof/thermal/CSP.py
> +    # losses (cleaniness)
```suggestion
    # losses (cleanliness)
```

2019-11-14 13:36 UTC, c-moeller commented on src/oemof/thermal/CSP.py
> +    return data
```suggestion
    
    return data
```

2019-11-14 13:41 UTC, c-moeller commented on src/oemof/thermal/CSP.py
> +    return data
The preheating losses are not included in the precalculation, right? Or did I miss it? Just to understand it right... :-)

2019-11-14 13:43 UTC, c-moeller commented
Looks good to me. I mainly made style corrections.
I did not check the example file, because I cannot run it because of missing data. How do we handle this?

2019-11-14 13:45 UTC, c-moeller requested changes
see comment above

2019-11-21 15:07 UTC, FranziPl commented on src/oemof/thermal/CSP.py
> +    return data
You are right, they are not included.

2019-12-12 08:33 UTC, c-moeller commented on examples/CSP/csp_collector_plot_example.py
> +from oemof.thermal.CSP import csp_precalc
from oemof.thermal.concentrating_solar_power import csp_precalc

2019-12-12 08:34 UTC, c-moeller commented on examples/CSP/csp_plant_example.py
> +from oemof.thermal.CSP import csp_precalc
`from oemof.thermal.concentrating_solar_power import csp_precalc`

2019-12-13 14:55 UTC, FranziPl commented
@c-moeller, I changed the import statement. I am ready to merge, if your review say so too.

2019-12-13 15:01 UTC, FranziPl commented
@c-moeller, I changed the import statement. I am ready to merge, if your review say so too.

2019-12-16 12:21 UTC, c-moeller commented on docs/concentrating_solar_power.rst
> +(an oemof.solph component) and a transformer (an oemof.solph component) can be
```suggestion
(an oemof.solph component), and a transformer (an oemof.solph component) can be
```

2019-12-16 12:22 UTC, c-moeller commented on docs/concentrating_solar_power.rst
> +Concecept
```suggestion
Concept
```

2019-12-16 12:22 UTC, c-moeller commented on docs/concentrating_solar_power.rst
> +In addition, you will find an example, which compares this precalculation fix a
Is this sentence wrong? I don't understand... :-)

2019-12-16 12:24 UTC, c-moeller commented on docs/concentrating_solar_power.rst
> +with
```suggestion
and
```

2019-12-16 12:25 UTC, c-moeller commented on docs/concentrating_solar_power.rst
> +the irradiance. Depending on method, this must be the horizontal direct
```suggestion
the irradiance. Depending on the method, this must be the horizontal direct
```

2019-12-16 12:27 UTC, c-moeller commented on examples/CSP/csp_collector_plot_example.py
> +plt.savefig('compare_temp_dependency.png')
You could think about inserting a plt.show()

2019-12-16 12:29 UTC, c-moeller approved these changes
I finished my review. All examples are running now. I added few small comments you could have a look at.

2019-12-16 12:45 UTC, FranziPl commented on examples/CSP/csp_collector_plot_example.py
> +plt.savefig('compare_temp_dependency.png')
Done

2019-12-16 12:45 UTC, FranziPl commented on docs/concentrating_solar_power.rst
> +In addition, you will find an example, which compares this precalculation fix a
There was a mistake, I changed it

2019-12-16 12:51 UTC, merged