Features/solarcollector
oemof/oemof-thermal pull request #22
Opened 2019-11-14 16:21 UTC by c-moeller

This PR is related to the issue https://github.com/oemof/oemof/issues/650

Not working yet.

2019-11-14 16:22 UTC, c-moeller commented
@FranziPl please wait with your review. We have to clarify the data issue first. I need a running example to continue.

2019-12-16 14:00 UTC, c-moeller commented
@FranziPl you can start your review. There are still some style errors even though I used black. I will check them later (have a meeting now).

2019-12-16 14:54 UTC, FranziPl requested changes

2019-12-16 14:54 UTC, FranziPl commented on src/oemof/thermal/flat_plate_collector.py
> +    Calculates collectors efficiency and irradiance of a flat plate collector.
Calculates collectors heat, efficiency and irradiance of a flat plate collector.

2019-12-16 14:54 UTC, FranziPl commented on src/oemof/thermal/flat_plate_collector.py
> +        the ambient temp (in Celsius degrees).
the ambient temperature (in Celsius degrees).

2019-12-16 14:54 UTC, FranziPl commented on docs/solar_thermal_collector.rst
> +The precalculations for the solar thermal collector calculate the heat of the solar collector based on the direct horizontal and the diffuse irradiance and information about the collector and the loc
"based on global and diffuse horizontal irradiance". 
Direct and diffuse would be possible, but the function used global and diffuse irradiance

2019-12-16 14:54 UTC, FranziPl commented on docs/solar_thermal_collector.rst
> +The processing of the irradiance data is done by the pvlib, which calculates the direct and diffuse irradiance on the collector area according to the azimuth and tilt angle of the collector.
calculates the total in-plane irradiance.

2019-12-16 14:54 UTC, FranziPl commented on docs/solar_thermal_collector.rst
> +    ========================= =================================================== ===========
delta_temp_n is missing

2019-12-16 14:58 UTC, FranziPl commented
The pictures for the documentation are missing and the table is malformed, so I coulnd't build it locally.

2019-12-17 10:04 UTC, c-moeller commented
@FranziPl the code is ready to review... Will you have a look at it? There are still some style errors I have to resolve, but I have a meeting now. I will do it afterwards.

2019-12-17 10:09 UTC, jnnr commented
Before merging this branch to dev, merge the current dev branch to this one get all the updates. Especially the configuration files for flake8 and pylint do not exist on this branch yet.

2019-12-17 10:12 UTC, jnnr commented on docs/solar_thermal_collector.rst
> +Please see the API for all Parameters, which have to be provided. The needed dataframe
lower case parameters

2019-12-17 10:13 UTC, jnnr commented on examples/flat_plate_collector/flat_plate_collector_example.py
> +# demand_df = pd.read_csv(
If this is unused, it should be removed.

2019-12-17 12:03 UTC, FranziPl commented
@c-moeller What needs a second review? I will look at docs again now. If the rest need another review too, please tell me, when I can have a look at the final version.

2019-12-17 12:07 UTC, c-moeller commented
@FranziPl yes only the docs.

2019-12-17 12:56 UTC, FranziPl requested changes
I commented a few things, the rest looks fine to me.

2019-12-17 12:56 UTC, FranziPl commented on docs/solar_thermal_collector.rst
> +    :start-after:  calc_eta_c_flate_plate_equation::
:start-after:  calc_eta_c_flate_plate_equation:
(with the second ":" it doesn't work)

2019-12-17 12:56 UTC, FranziPl commented on docs/solar_thermal_collector.rst
> +The three values :math:`Q_{coll}`, :math:`\eta_C` and :math:`E_{coll}` are returned.
are returned in a dataframe.

2019-12-17 12:56 UTC, FranziPl commented on src/oemof/thermal/flat_plate_collector.py
> +    with
a blank line before and after "with" makes the docu more readable.

2019-12-17 12:56 UTC, FranziPl commented on docs/solar_thermal_collector.rst
> +    :math:`Q_{coll}`          :py:obj:`collector_heat`         collectors heat
Collectors heat

2019-12-17 12:56 UTC, FranziPl commented on docs/solar_thermal_collector.rst
> +    :math:`\eta_C`            :py:obj:`eta_c`                  collectors efficiency
Collectors efficiency

2019-12-17 13:00 UTC, FranziPl commented on docs/solar_thermal_collector.rst
> +    :math:`T_{collector in}`  :py:obj:`temp_collector_inlet`   Collectors inlet temperature
```suggestion
    :math:`T_{Collector, in}`  :py:obj:`temp_collector_inlet`   Collectors inlet temperature
```

2019-12-17 13:21 UTC, c-moeller commented
@FranziPl Had to cancel one of your suggestion due to Pep8 reasons. Please approve. Thank you!

2019-12-17 13:29 UTC, FranziPl approved these changes

2019-12-17 13:30 UTC, FranziPl commented on src/oemof/thermal/flat_plate_collector.py
> +    with
```suggestion

    with

```

2019-12-17 13:35 UTC, c-moeller commented on src/oemof/thermal/flat_plate_collector.py
> +    with
This does not work due to Pep8 reasons :-(

2019-12-17 13:49 UTC, merged

2019-12-17 14:01 UTC, FranziPl commented on src/oemof/thermal/flat_plate_collector.py
> +    with
It does. I commited it before you merged.