Improvement of documentation of thermal storage
oemof/oemof-thermal pull request #42
Opened 2020-01-07 12:34 UTC by FranziPl

This PR will slightly change the documentation of the thermal storage.
It includes #40.

2020-01-07 13:29 UTC, jakob-wo commented on docs/stratified_thermal_storage.rst
> +* :math:`\gamma \cdot Q_N`: losses via the lateral surface depending on the
```suggestion
* :math:`\gamma \cdot Q_N`: losses through the total lateral surface assuming the storage to be empty (storage is at :math:`T_{C}` and :math:`\Delta T_{C0}` is the driving temperature difference)
```

2020-01-07 13:30 UTC, jakob-wo commented on docs/stratified_thermal_storage.rst
> +* :math:`\gamma \cdot Q_N`: losses via the lateral surface depending on the
What about a bit more explaination?

2020-01-07 13:30 UTC, jakob-wo commented on docs/stratified_thermal_storage.rst
> +height of the storage
```suggestion
```

2020-01-07 13:30 UTC, jakob-wo commented on docs/stratified_thermal_storage.rst
> +height of the storage
Has to be removed if suggestion above is exepted.

2020-01-07 13:32 UTC, jakob-wo commented on docs/stratified_thermal_storage.rst
> +* :math:`\beta \cdot Q_{t-1}`: losses depending on the part of that surface
```suggestion
* :math:`\beta \cdot Q_{t-1}`: addional losses through lateral surface that
```

2020-01-07 13:33 UTC, jakob-wo commented on docs/stratified_thermal_storage.rst
> +belonging to the hot part of the water body that depend on the state of charge
```suggestion
belong to the hot part of the water body
```

2020-01-08 09:36 UTC, jnnr requested changes

2020-01-08 09:36 UTC, jnnr commented on docs/stratified_thermal_storage.rst
> +
I would suggest to remove this part. It is uncommon to explain different instances of an indexed variable.

2020-01-08 09:51 UTC, jnnr commented
Thanks for your effort! Just some minor flaws. If you build the docs, the bulletpoints do not render nicely. Try adding some whitespace and a tab after linebreak. The rest looks good. If you want, I can give another review after you decided about the changes.

2020-01-08 12:38 UTC, FranziPl commented on docs/stratified_thermal_storage.rst
> +
Thats fine for me, but we should descirbe Q in generell

2020-02-26 10:06 UTC, FranziPl commented on docs/stratified_thermal_storage.rst
> +* :math:`\gamma \cdot Q_N`: losses via the lateral surface depending on the
```suggestion
* :math:`\gamma \cdot Q_N`: losses through the total lateral surface assuming the storage to be empty (storage is at :math:`T_{C}` and :math:`\Delta T_{C0}` is the driving temperature difference), depending on the height of the storage
```

2020-02-26 10:06 UTC, FranziPl commented on docs/stratified_thermal_storage.rst
> +belonging to the hot part of the water body that depend on the state of charge
```suggestion
belong to the hot part of the water body, depending on the state of charge
```

2020-02-26 10:12 UTC, FranziPl commented on docs/stratified_thermal_storage.rst
> +
I removed Q_t and Q_t-1 and just added Q.

2020-02-26 10:13 UTC, FranziPl commented
I considered the comments and I think, it is ready for merging now.

2020-02-26 13:35 UTC, jnnr commented
I added a caption, corrected a wrong name in the schematic and rearranged the bullet list.

2020-02-26 13:35 UTC, jnnr approved these changes

2020-02-26 13:35 UTC, merged