Add tests for module compression_heatpumps_and_chillers
oemof/oemof-thermal pull request #57
Opened 2020-01-22 13:27 UTC by jakob-wo

1) This PR adds tests for the module `compression_heatpumps_and_chillers.py`.

It also includes two additional changes (I know, I should have done this in seperate PRs - sry!)
2) The PR fixes the docstring of a pre-calculation-function. Before it said the input argument had to be of type list but in fact it can be a pandas.Series as well. I added that information to the docstring.

3) The PR adds Exceptions to the module: It is checked whether the input arguments have the proper type and length.

2020-01-22 16:47 UTC, jnnr requested changes

2020-01-22 16:47 UTC, jnnr commented on src/oemof/thermal/compression_heatpumps_and_chillers.py
> +    # Check if input arguments have proper type and length
Would be good to insert spaces between the different if / elif / else statements for readability

2020-01-22 16:47 UTC, jnnr commented on src/oemof/thermal/compression_heatpumps_and_chillers.py
> +    temp_high : list or pandas.Series of numerical values
If you want to allow for the new datatype, you should also write a test for that feature.

2020-01-22 16:47 UTC, jnnr commented on src/oemof/thermal/compression_heatpumps_and_chillers.py
> +    if factor_icing is not None and consider_icing is False:
To make this easier, I would suggest to drop `consider_icing` and keep only `factor_icing`. Then check if `factor_icing` is not None and include it in the calculations if that is the case.

2020-01-22 16:47 UTC, jnnr commented on src/oemof/thermal/compression_heatpumps_and_chillers.py
> +    if type(temp_low) == pd.Series:
```suggestion
    if not (isinstance(temp_low, (pd.Series, list))):
        raise TypeError('Argument temp_low is not of type list or pd.Series.')
```

2020-01-22 16:48 UTC, jnnr commented
Thanks for the tests! Looks good, just some minor remarks.

2020-01-23 15:41 UTC, jakob-wo commented
Good feedback! 
I like your ideas, implemented all requested changes and adjusted the examples to work without the argument 'consider_icing'.

2020-01-27 15:37 UTC, jnnr commented on src/oemof/thermal/compression_heatpumps_and_chillers.py
> +            raise ValueError('Argument factor ising has '
```suggestion
            raise ValueError('Argument factor_icing has '
```

2020-01-27 15:38 UTC, jnnr commented on src/oemof/thermal/compression_heatpumps_and_chillers.py
> +                             'to be None for mode=chiller!')
```suggestion
                             "to be None for mode='chiller'!")
```

2020-01-27 15:38 UTC, jnnr commented on src/oemof/thermal/compression_heatpumps_and_chillers.py
> +        raise TypeError('Argument cops is not of type list!')
```suggestion
        raise TypeError("Argument 'cops' is not of type list!")
```

2020-01-27 15:41 UTC, jnnr commented
Thanks, looks good. Just a little suggestion in for the error messages. Apart from that, it could be merged.

In another PR, you could implement the functionality of giving back a pd.Series as result when passing one as input. But that can be dealt with separately.

2020-01-27 15:42 UTC, jnnr approved these changes

2020-02-12 10:35 UTC, merged