Features/improve docu pics
oemof/oemof-thermal pull request #76
Opened 2020-02-21 14:18 UTC by FranziPl

This PR will add a schematic of the csp, which will match the schematics of the other components.
It will solve #61.
@jakob-wo or @jnnr: Can either of you look at it?

2020-02-24 10:22 UTC, jnnr commented
Thanks, that looks good! Really helpful to have that image.

Some remarks:

* The image canvas is quite large, leading to a lot of blank space in the docs. You could shrink it to the size of the actual picture.
* Illustrating the geometrical losses with curly arrows suggests that the losses are somehow scattered/dissipated, which could be misleading.
* Q_coll is the difference between the heat entering and the heat leaving the collector. Maybe rather write mass flows and temperatures to the arrows?
* The red arrow should be parallel to the contour of the mirror.

2020-02-26 08:10 UTC, FranziPl commented
I changed point 1, 3, and 4. I disagree to the second point, because I think that there are many arrows and information in this picture. And if I don't have a consistent form for the different types of loss, it would be confusing. Besides, I have followed your picture in this point.

2020-02-26 09:48 UTC, FranziPl commented
Point 2 is now also considered.
Ready to merge in my opinion. 
I would like to have another review.

2020-03-12 16:43 UTC, c-moeller commented
@FranziPl Do you plan such kind of pic for the solar thermal collector as well? Otherwise @MaGering could do this.

2020-03-12 16:48 UTC, c-moeller commented on docs/concentrating_solar_power.rst
> +the collector can provide.
What do you think about changing this text to something like the following (I took this from the specification sheet of the component):

> The direct normal radiation (E_dir) is reduced by geometrical losses (Q_loss,geom) so that only the collector radiation (E_coll*) hits the collector. Before the thermal power is absorbed by the absorber tube, also optical losses (Q_loss,opt), which can be reflection losses at the mirror, transmission losses at the cladding tube and absorption losses at the absorber tube, occur. The absorber finally loses a part of the absorbed heat output through thermal losses (Q_loss,therm).

It might be a bit easier to capture the picture.

2020-03-13 08:26 UTC, FranziPl commented
> 
> 
> @FranziPl Do you plan such kind of pic for the solar thermal collector as well? Otherwise @MaGering could do this.

I didn't plan it, but it is a svg file, to it is possible to adapt it.

2020-03-16 10:38 UTC, jnnr commented on docs/concentrating_solar_power.rst
> +the collector can provide.
I agree. It would be helpful to explain the different processes that the incoming radiation undergoes until it is finally converted to usable heat a bit more, so the reader can understand the picture and relate that to the math following below.

2020-03-16 10:44 UTC, jnnr commented
Hey @FranziPl, thanks for the picture. It looks really good! Really helps understanding.

Just some small things: You could consider extending the text in the caption. In my experience, the pictures are the parts in a long text that you grasp first, so it is always good to ship it with some text that just explains what we see on the picture.

I would also agree with @c-moeller with their comment above.

2020-03-23 12:28 UTC, MaGering commented
> I would like to have another review.

Unfortunately svg figures won't render in pdfLaTeX: https://github.com/oemof/oemof-thermal/pull/91

Hence a .png-file  of 'concentrating_solar_power.svg' needs to be embedded in 'concentrating_solar_power.rst'.

2020-03-24 13:38 UTC, jnnr commented
Should the losses in the image, math:`Q`, not rather be declared as  math:`\dot{Q}`?

2020-03-24 15:43 UTC, MaGering commented
I've added a svg schematic of the solar thermal collector to the folder _pics.

2020-03-27 17:23 UTC, FranziPl commented on docs/concentrating_solar_power.rst
> +the collector can provide.
I integrated the text

2020-03-27 17:33 UTC, FranziPl commented
I am done. I changed the picture from svg to png, I added a line to the whats new file and I integrated the comments of jnnr and c-moeller.
If I didn't miss anything, it can be merged.

2020-03-30 11:43 UTC, jnnr commented
> Should the losses in the image, math:`Q`, not rather be declared as math:`\dot{Q}`?

I saw that this is adapted for the csp. I guess this should be adapted for the solar_thermal_collector as well, shouldn't it, @MaGering?

2020-04-01 14:57 UTC, jnnr requested changes
As written in a previous comment, I think that in the image showing the solar thermal collector, Q has to become dot Q. Do you agree, or am I wrong, @MaGering?

2020-04-01 15:00 UTC, FranziPl commented
@MaGering did the requested change in #84 instead of this one, but it is done.

2020-04-01 17:35 UTC, jnnr approved these changes

2020-04-01 17:37 UTC, jnnr commented
> @MaGering did the requested change in #84 instead of this one, but it is done.

Ok. In this case I approve. From my view this seems ready to be merged.

2020-04-02 06:33 UTC, FranziPl commented
Travis doesn't work here, it is still waiting for a status.
I checked pytest and flake8 locally, so the branch is ok and could be merged.
But I have no idea, why travis has a problem here. Does anybody have an idea? Should I merge anyway?

2020-04-03 08:25 UTC, merged