Features/improve code csp
oemof/oemof-thermal pull request #84
Opened 2020-03-05 13:32 UTC by FranziPl

As mentioned in #79 the code for the csp precalculation is not in its best shape. So I changed the structur a little bit:
* There is a 'main function' which uses other function. Every single other function has an own definition.
* The input is not a dataframe enymore, but parameters to set the correct datetimeindex and series for the irradiance and the temperature
* There are more warnings, if wrong parameters are given

In this PR additionally the examples and tests should be adapted:
[X] csp plant axample
[] csp plot example is adapted
[] tests are adapted

Please let me know, if I forgot something and what you think about it in general.

2020-03-05 15:08 UTC, FranziPl commented
So I changes all the files, which are necessary.
Could one of you review the PR please?
Thanks.

2020-03-12 13:57 UTC, c-moeller commented
I cannot run the csp_collector_plot_example_andasol.py

`AttributeError: 'E_dir_hor' necessary for horizontal is not provided    `

2020-03-12 17:09 UTC, c-moeller commented
Looks good to me except for the not running example.
@jnnr Could you have a detailled look on the code since I don't know exactly what you discussed during your meeting.

2020-03-16 14:37 UTC, jnnr commented
Generally, I find the docstrings much easier to read if there is one empty line between Parameters. I saw that in oemof/oemof, there are no spaces as well, but still it would be an improvement I think.

2020-03-16 17:49 UTC, jnnr commented on src/oemof/thermal/concentrating_solar_power.py
> +    if 'temp_amb_input' not in kwargs:
If temp_amb has to be provided in all cases, it would be simpler to list it among the arguments of the function together with the others:

`temp_collector_inlet, temp_collector_outlet, temp_amb`

Then you could just drop this check here.

2020-03-16 17:49 UTC, jnnr commented on src/oemof/thermal/concentrating_solar_power.py
> +    date_time_index = pd.date_range(date, periods=periods,
Here, a new timeindex is created.

In #79, I proposed to pass the timeseries that are input to the function as pd.Series with an timeindex. Then, the function could just check if the three series all have the same timeindex, and no new timeindex had to be created. However, as the pv-lib needs a timeindex, this would not allow the user to pass a list instead of a pd.Series. Maybe this would be good, as the user has to explicitly prepare the pd.Series with timeindex (which would be ok, a standard thing to ask), rather than letting that happening internally. What do you think?

2020-03-17 09:07 UTC, jnnr commented
I tried running the examples and got two errors:

* python csp_collector_plot_example_andasol.py 
```
Traceback (most recent call last):
  File "csp_collector_plot_example_andasol.py", line 47, in <module>
    date_col='Datum', temp_amb_col='t_amb')
  File "oemof-thermal/src/oemof/thermal/concentrating_solar_power.py", line 136, in csp_precalc
    f"'{irradiance_required}' necessary for {irradiance_method} is not provided")
AttributeError: 'E_dir_hor' necessary for horizontal is not provided
```

* python csp_plant_example.py 

```
Traceback (most recent call last):
  File "csp_plant_example.py", line 113, in <module>
    storage = solph.components.GenericStorage(
AttributeError: module 'oemof.solph' has no attribute 'components'
```

I do not fully understand the second error, but I can fix it by importing the GenericStorage directly, i.e.

`from oemof.solph.components import GenericStorage`

2020-03-19 10:35 UTC, c-moeller commented
I get the same error like @jnnr when running csp_collector_plot_example_andasol.py

but no error on csp_plant_example.py

2020-03-24 10:26 UTC, FranziPl commented on src/oemof/thermal/concentrating_solar_power.py
> +    if 'temp_amb_input' not in kwargs:
I changed it to a positional argument and dropped the check.

2020-03-24 10:27 UTC, FranziPl commented on src/oemof/thermal/concentrating_solar_power.py
> +    date_time_index = pd.date_range(date, periods=periods,
I changed the structure, so now time indexed series has to be given to the function.

2020-03-24 10:33 UTC, FranziPl commented
I adapted your comments and the examples work again.

2020-03-27 17:44 UTC, FranziPl commented
I added a line to the whats new and adapted the docu.
In my opinion, it is ready to merge now.

2020-03-31 17:01 UTC, c-moeller requested changes
Looks great to me. Examples are working, too.

Just two small remarks, which I think can be quickly done:
- In the example 'cps_collector_plot_example_andasol.py' you do not plot units in both figures except for the time, but style should be consistent
- In the example 'csp_collector_plot_example.py' you do not plot a unit in the second figure on ambient_temperature --> should be °C

And a question: is it Q or Q_dot? Or no difference because we have 1 hour time steps?
I think this question appeared here as well: https://github.com/oemof/oemof-thermal/pull/76

2020-03-31 17:01 UTC, c-moeller commented on docs/concentrating_solar_power.rst
> +losses (Q_loss,therm).
The text somehow appears in italic letters (maybe because of the asterisk). Did you check if this happens in the compiled documentation as well? Perhaps it's only the preview which is strange here.

2020-03-31 17:01 UTC, c-moeller commented on docs/concentrating_solar_power.rst
> +this functions amd the loss method "Janotte" in comparison to the heat
```suggestion
this functions and the loss method "Janotte" in comparison to the heat
```

2020-03-31 17:01 UTC, c-moeller commented on docs/whats_new/v0-0-2.rst
> +series now, instead of a series and separate information about the date
```suggestion
* concentrating solar power: The input for irradiance is now a time indexed
series instead of a series and separate information about the date
```

2020-03-31 17:01 UTC, c-moeller commented on src/oemof/thermal/concentrating_solar_power.py
>      Calculates collectors efficiency and irradiance according to [1] and the
```suggestion
    Calculates collector efficiency and irradiance according to [1] and the
```

2020-03-31 17:01 UTC, c-moeller commented on src/oemof/thermal/concentrating_solar_power.py
> +        Ambient temperature time series
```suggestion
        Ambient temperature time series.
```

2020-03-31 17:01 UTC, c-moeller commented on src/oemof/thermal/concentrating_solar_power.py
> +        collectors efficiency.
```suggestion
        Collector efficiency.
```

2020-04-01 08:49 UTC, FranziPl commented on docs/concentrating_solar_power.rst
> +losses (Q_loss,therm).
It looks normal in the compiled document.

2020-04-01 08:57 UTC, FranziPl commented
You are right, I added the missing units.
It is Q_dot, but Q_dot_coll doesn't seem nice to read, thats why I just wrote Q_coll. But in the units you can see, that is is power, not energy.

2020-04-01 12:18 UTC, c-moeller approved these changes

2020-04-01 15:00 UTC, jnnr commented
Shall I review this again? I can do so on Friday.

2020-04-01 15:03 UTC, FranziPl commented
@jnnr, I am not sure if it is necessary. Maybe it is a good idea for the file
\src\oemof\thermal\concentrating_solar_power.py, as I integrated a lot of your suggestions there.
The rest is fine.

2020-04-03 13:54 UTC, jnnr commented on src/oemof/thermal/concentrating_solar_power.py
> +    irradiance = (kwargs.get(irradiance_required))
Why are there brackets? Does this have to be a tuple?

2020-04-03 14:04 UTC, jnnr commented on src/oemof/thermal/concentrating_solar_power.py
> +    irradiance: time indexed series
```suggestion
    E_dir_hor/dni (depending on irradiance_method): time indexed series
```

2020-04-03 14:07 UTC, jnnr commented on src/oemof/thermal/concentrating_solar_power.py
> +    irradiance = (kwargs.get(irradiance_required))
It seems that the brackets can be removed. Tests and examples keep running.

2020-04-03 14:36 UTC, jnnr approved these changes
Thanks for your effort! I fixed a test that did not get executed before, added another one checking for an index error and added two lines that check and raise an index error when temp_amb and irradiance do not have the same index. Also, I posted two comments, one for the docstring and one for the code. Apart from that, I am ok with merging this.

2020-04-03 15:42 UTC, FranziPl commented on src/oemof/thermal/concentrating_solar_power.py
> +    irradiance = (kwargs.get(irradiance_required))
I have no idea, why they are there, I removed them

2020-04-03 15:43 UTC, merged